### ISSUE TITLE
Support for accessing different X11 clipboards

### ISSUE THREAD

**Issue by complexspaces** [ArturKovacs/arboard#16]
Hi there,

While looking at migrating from `x11-clipboard` to `arboard`, I noticed that some of the more "advanced" configuration options are gone, such as being able to control the atoms used in get and store operations.

It would be nice if `arboard` exposed functionality in some way that would allow users to, optionally, change [which X11 clipboard](https://specifications.freedesktop.org/clipboards-spec/clipboards-0.1.txt) operations are performed on.

A rough non-breaking change could be something like this:

```rust
pub enum X11ClipboardChoice {
  Clipboard
  Primary,
  Secondary,
}

impl X11ClipboardContext {
   pub fn get_text(&self) -> Result<String, Error> { ... }
   
   pub fn get_text_with_clipboard(&self, clipboard: X11ClipboardChoice) -> Result<String, Error> { ... } 
}
```

Is this a feature you would consider adding or accepting work for?

**Comment by ArturKovacs** [comment]
Hello there!

Thanks for opening an issue. Yes, I would totally consider merging a PR for this. In fact thought about this myself, but other things took priority.

The API you proposed is almost perfect, but I would rather expose this function on the `arboard::Clipboard` type maybe through an extension trait like this:

```rust
// common_linux.rs

pub enum LinuxClipboardKind {
	Clipboard
	Primary,
	Secondary,
}
trait ClipboardExtLinux {
	pub fn set_text_with_clipboard(&self, text: String, clipboard: LinuxClipboardKind) -> Result<(), Error>;
	pub fn get_text_with_clipboard(&self, clipboard: LinuxClipboardKind) -> Result<String, Error>;
}

impl ClipboardExtLinux for super::Clipboard {
	pub fn get_text_with_clipboard(&self, clipboard: LinuxClipboardKind) -> Result<String, Error> {
		match self.platform {
			...
		}
	}
}
```

Change the visibility to `pub(crate)`
```rust
// lib.rs
pub struct Clipboard {
	pub(crate) platform: PlatformClipboard,
}
```
