### ISSUE TITLE
Replace or add an alternative to `xcb` with `x11rb`

### ISSUE THREAD

**Issue by daxpedda** [ArturKovacs/arboard#8]
Considering that `xcb` has been marked by `cargo-audit` as problematic: https://rustsec.org/advisories/RUSTSEC-2021-0019.html
Would a PR to replace it with `x11rb` be accepted, or at least use it as an alternative with the help of a crate feature?

**Comment by ArturKovacs** [comment]
Hmm I didn't know about this. Yes, a PR that replaces `xcb` with `x11rb` would be appreciated. 😊
